### ISSUE TITLE
Error Stack

### ISSUE THREAD

**Issue by blablubbabcDEV** [blablubbabc/AntiXRay#11]
**Migrated from:** https://dev.bukkit.org/projects/anti-x-ray/issues/8

**Originally posted by _ForgeUser11956647 (Apr 16, 2014):** 

What steps will reproduce the problem?
1. Flying around and loading chunks.
2.
3.What is the expected output? What do you see instead?
Expected: Not a string of errors. Instead I see a string of errors (honestly not really sure what to make of them)What version of the product are you using?
Latest update.Do you have an error log of what happened?
16.04 04:25:52 [Server] INFO at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkitbeta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
16.04 04:25:52 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkitbeta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
16.04 04:25:52 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkitbeta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
16.04 04:25:52 [Server] INFO at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkitbeta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
16.04 04:25:52 [Server] INFO at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:587) [craftbukkitbeta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
16.04 04:25:52 [Server] INFO at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [craftbukkitbeta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
16.04 04:25:52 [Server] INFO at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkitbeta.jar:git-Bukkit-1.7.2-R0.3-b3020jnks]
16.04 04:25:52 [Server] INFO at me.ryanhamshire.AntiXRay.DeliverPointsTask.run(DeliverPointsTask.java:40) ~[?:?]
16.04 04:25:52 [Server] INFO at me.ryanhamshire.AntiXRay.DataStore.getOrCreatePlayerData(DataStore.java:56) ~[?:?]
16.04 04:25:52 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.OfflinePlayer.getUniqueId()Ljava/util/UUID;
16.04 04:25:52 [Server] WARN Task #51 for AntiXRay v1.8 generated an exceptionPlease provide any additional information below.
Was just flying around, loading chunks. I recently replaced Orbfuscator with your plugin as the prior was causing corrupted chunks when combined with NoLagg. I get these errors and notice considerable lag, high memory usage and low tps when loading chunks. Using the 1.7.2 beta build of Bukkit. Thanks in advance for any help you can offer.

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Apr 16, 2014):** 

Seems like you have to update your server for the 1.8 version to mc 1.7.8
However, I think I might be able to make the 1.8 update of AntiXRay backward compatible with other 1.7.x bukkit builds. So expect another update shortly, and let me know if that works then.

**Comment by blablubbabcDEV** [comment]
**Originally commented by blablubbabc (Apr 16, 2014):** 

Alright, I uploaded v1.8.1, which should work on lower 1.7.x bukkit versions as well. Let me know if it works.

**Comment by blablubbabcDEV** [comment]
**Originally closed by blablubbabc (Apr 16, 2014)**
